name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  ui-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 对 CI 隐藏本地驱动，强制走 webdriver-manager
    # - name: Hide local drivers for CI
    #  run: mv drivers _drivers_off 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome & Driver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Run UI tests
      env:
        HEADLESS: true
      run: |
        pytest tests/ui -q

    - name: Upload Allure report（可选）
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results/