name: CI

on:
  push:
    branches: [ test-clean ]
  pull_request:
    branches: [ test-clean ]
  schedule:
    - cron: '11 14 * * *'

jobs:
  ui-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome & Driver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Run UI tests
      env:
        HEADLESS: true
      run: |
        pytest tests/ui -v